name: py_scripts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # 时间是按UTC设置的，实际执行时间，则自动按东八区执行
    # 即+8小时，故实际执行时间为：8点，20点
    - cron: 0 2,14 * * *

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7]
        #python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        python setup.py install
    # - name: Lint with flake8
    #  run: |
    #    pip install flake8
    #    # Stop the build if there are flake8 issues
    #    flake8 . --count --show-source --statistics --exclude=temp
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
        sudo apt-get install firefox
    - name: Install chromedriver and geckodriver (Firefox Webdriver)
      run: |
        seleniumbase install chromedriver
        seleniumbase install geckodriver
    #- name: Make sure pytest is working
    #  run: |
    #    echo "def test_1(): pass" > nothing.py
    #    pytest nothing.py
    
#     # 天翼云盘签到+抽奖
#     - name: Cloud 189 Checkin
#       env:
#         CLOUD189_USER: ${{ secrets.CLOUD189_USER }}
#         CLOUD189_PWD: ${{ secrets.CLOUD189_PWD }}
#       run: |
#         bash scripts/_C189.sh
    
#     # HostLoc 赚积分
#     - name: 'HostLoc Get points'
#       env:
#         HOSTLOC_COOKIE_SALTKEY : ${{ secrets.HOSTLOC_COOKIE_SALTKEY  }}
#         HOSTLOC_COOKIE_AUTH: ${{ secrets.HOSTLOC_COOKIE_AUTH }}
#         NOTIFY_URL: ${{ secrets.NOTIFY_URL }}
#         HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
#         HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
#       run: python scripts/hostloc/hostloc_get_points.py
    
    # TextNow保号任务
    - name: textnow protect number
      env:
        TEXTNOW_USERNAME: ${{ secrets.TEXTNOW_USERNAME }}
        TEXTNOW_PASSWORD: ${{ secrets.TEXTNOW_PASSWORD }}
        TEXTNOW_NUMBER: ${{ secrets.TEXTNOW_NUMBER }}
        TEXTNOW_MSG: ${{ secrets.TEXTNOW_MSG }}
      run: |
        python scripts/_textnow.py
    - name: Checkout
      uses: actions/checkout@master
    - name: log push  #获得自动部署的时间
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit #上传到仓库
      run: |
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name AutoupdateRobot
        git add .
        git commit -m "update new push" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
